// Generated by CoffeeScript 1.7.1
(function() {
  var app, cs_opts, dark_roast, interpret, pkg, validate;

  app = require('commander');

  dark_roast = require('./dark_roast');

  pkg = require('./../package');

  validate = function(path_to_coffee, opts) {
    var msg;
    if (!app.blend) {
      msg = 'I need a --blend extension (ex: .co).';
    } else if (!path_to_coffee) {
      msg = 'I need a path to coffee files.';
    }
    if (msg) {
      console.error(msg);
      return process.exit(1);
    }
  };

  cs_opts = function(args) {
    return args.slice(args.indexOf('--') + 1).join(' ');
  };

  interpret = function() {
    var path_to_cs;
    app.version(pkg.version).usage('[options] path/to/script.coffee -- [coffee-script-options]').option('--blend [file_extension]', 'File extension to use.').parse(process.argv);
    path_to_cs = app.args[0];
    validate(path_to_cs, app);
    return dark_roast.compile(path_to_cs, cs_opts(process.argv), app);
  };

  module.exports = {
    interpret: interpret
  };

}).call(this);
