// Generated by CoffeeScript 1.7.1
(function() {
  var create, fs, minilog;

  minilog = require("minilog");

  fs = require("fs");

  minilog.pipe(minilog.backends.nodeConsole.formatLearnboost).pipe(minilog.backends.nodeConsole);

  create = function(name) {
    return minilog(name);
  };

  module.exports = {
    create: create
  };

}).call(this);
